// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf8aDP-MnADARybJWNY8C3FZiA5KUfIIQ',
    appId: '1:446566732712:web:821cb3476c5c8e6d86839d',
    messagingSenderId: '446566732712',
    projectId: 'chat-flutter-app-e0d15',
    authDomain: 'chat-flutter-app-e0d15.firebaseapp.com',
    storageBucket: 'chat-flutter-app-e0d15.appspot.com',
    measurementId: 'G-PCRBM86RGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTh64vtOaCPy-WDcUEf9QG4zHVJYcpXWQ',
    appId: '1:446566732712:android:29beb16a17e76e4f86839d',
    messagingSenderId: '446566732712',
    projectId: 'chat-flutter-app-e0d15',
    storageBucket: 'chat-flutter-app-e0d15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Cte0PlnweBHU_va1GWFAF-OPpmSNPhM',
    appId: '1:446566732712:ios:b2fc40aad60c49ee86839d',
    messagingSenderId: '446566732712',
    projectId: 'chat-flutter-app-e0d15',
    storageBucket: 'chat-flutter-app-e0d15.appspot.com',
    iosBundleId: 'com.example.chatFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Cte0PlnweBHU_va1GWFAF-OPpmSNPhM',
    appId: '1:446566732712:ios:828ebe8940ae6cf486839d',
    messagingSenderId: '446566732712',
    projectId: 'chat-flutter-app-e0d15',
    storageBucket: 'chat-flutter-app-e0d15.appspot.com',
    iosBundleId: 'com.example.chatFlutterApp.RunnerTests',
  );
}
